# Generated by Django 5.2.4 on 2025-07-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
