version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - searchnet

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - searchnet

  # Placeholder for Django app
  web:
    build: .
    command: tail -f /dev/null  # keep container alive
    volumes:
      - .:/code
    depends_on:
      - elasticsearch
      - redis
    networks:
      - searchnet

networks:
  searchnet:
    driver: bridge
